server:
  address: 'tcp://0.0.0.0:9091'

log:
  level: info

theme: auto

identity_validation:
  reset_password:
    jwt_secret: 'insecure_jwt_secret_change_me'

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 3
      memory: 65536
      parallelism: 4
      key_length: 32
      salt_length: 16

session:
  name: authelia_session
  same_site: lax
  secret: 'insecure_session_secret_change_me'
  expiration: 1h
  inactivity: 5m
  cookies:
    - name: authelia_session
      domain: localtest.me
      authelia_url: https://n8n.localtest.me:8443/authelia/
      default_redirection_url: https://n8n.localtest.me:8443/
      same_site: lax
  redis:
    host: redis
    port: 6379
    password: ''
    database_index: 0

storage:
  encryption_key: 'insecure_storage_secret_change_me'
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

access_control:
  default_policy: one_factor
  rules:
    - domain: localtest.me
      policy: one_factor
